from _rest import add, fill_remaining

def A(src, es, en, fr, de, pt, it, ja, ko, zh):
    add(src, es, en, fr, de, pt, it, ja, ko, zh)

A("⚠️ **Repair Failed:** The bot crashed during startup. Changes have been automatically reverted to the latest backup.",
  "⚠️ **Reparación fallida:** el bot se cayó al arrancar. Se ha vuelto al último backup.",
  "⚠️ **Repair Failed:** The bot crashed during startup. Changes have been automatically reverted to the latest backup.",
  "⚠️ **Réparation échouée :** le bot a planté au démarrage. Retour automatique au dernier backup.",
  "⚠️ **Reparatur fehlgeschlagen:** Der Bot ist beim Start abgestürzt. Automatisch auf das letzte Backup zurückgesetzt.",
  "⚠️ **Reparação falhou:** o bot crashou ao arrancar. Voltou-se ao último backup.",
  "⚠️ **Riparazione non riuscita:** il bot è crashato all'avvio. Ripristinato l'ultimo backup.",
  "⚠️ **修復失敗:** 起動時にクラッシュしました。最新バックアップに戻しました。",
  "⚠️ **복구 실패:** 시작 중 봇이 충돌했습니다. 최신 백업으로 되돌렸습니다.",
  "⚠️ **修复失败：** 机器人启动时崩溃。已自动回退到最新备份。")
A("⚠️ AI Conflict Alert: Heated Argument in Progress", "⚠️ Alerta de conflicto IA: discusión encendida", "⚠️ AI Conflict Alert: Heated Argument in Progress", "⚠️ Alerte conflit IA : discussion tendue", "⚠️ KI-Konflikt: hitzige Debatte", "⚠️ Alerta de conflito IA: discussão acesa", "⚠️ Allerta conflitto IA: discussione accesa", "⚠️ AI衝突アラート: 激しい議論", "⚠️ AI 충돌 경보: 격한 논쟁", "⚠️ AI 冲突警报：争论升温")
A("⚠️ Are you sure you want to delete **all** your notes?", "⚠️ ¿Seguro que quieres borrar **todas** tus notas?", "⚠️ Are you sure you want to delete **all** your notes?", "⚠️ Tu veux vraiment supprimer **toutes** tes notes ?", "⚠️ Willst du wirklich **alle** Notizen löschen?", "⚠️ Tens a certeza de apagar **todas** as tuas notas?", "⚠️ Vuoi davvero eliminare **tutte** le tue note?", "⚠️ **すべての**メモを削除してよいですか？", "⚠️ **모든** 메모를 삭제할까요?", "⚠️ 确定要删除**全部**备注吗？")
A("⚠️ Confirm Server Restore", "⚠️ Confirma la restauración del servidor", "⚠️ Confirm Server Restore", "⚠️ Confirme la restauration du serveur", "⚠️ Server-Wiederherstellung bestätigen", "⚠️ Confirma o restauro do servidor", "⚠️ Conferma il ripristino del server", "⚠️ サーバー復元を確認", "⚠️ 서버 복원 확인", "⚠️ 确认恢复服务器")
A("⚠️ Era la última. He restaurado las categorías predefinidas (Soporte, Reporte, Sugerencia, Otro).",
  "⚠️ Era la última. He restaurado las categorías predefinidas (Soporte, Reporte, Sugerencia, Otro).",
  "⚠️ That was the last one. I restored the default categories (Support, Report, Suggestion, Other).",
  "⚠️ C'était la dernière. J'ai restauré les catégories par défaut (Support, Signalement, Suggestion, Autre).",
  "⚠️ Das war die letzte. Standardkategorien wiederhergestellt (Support, Meldung, Vorschlag, Sonstiges).",
  "⚠️ Era a última. Restaurei as categorias predefinidas (Suporte, Reportar, Sugestão, Outro).",
  "⚠️ Era l'ultima. Ho ripristinato le categorie predefinite (Supporto, Segnalazione, Suggerimento, Altro).",
  "⚠️ 最後の1つでした。既定カテゴリ（サポート、報告、提案、その他）を復元しました。",
  "⚠️ 마지막이었습니다. 기본 카테고리(지원, 신고, 제안, 기타)를 복원했습니다.",
  "⚠️ 那是最后一个。已恢复默认分类（支持、举报、建议、其他）。")
A("⚠️ Esto **borra todos los canales y roles** de **{name}**.\nEscribe el nombre exacto del servidor para confirmar. No hay marcha atrás.",
  "⚠️ Esto **borra todos los canales y roles** de **{name}**.\nEscribe el nombre exacto del servidor para confirmar. No hay marcha atrás.",
  "⚠️ This **deletes every channel and role** in **{name}**.\nType the exact server name to confirm. There is no undo.",
  "⚠️ Ceci **supprime tous les salons et rôles** de **{name}**.\nTape le nom exact du serveur pour confirmer. Pas de retour.",
  "⚠️ Das **löscht alle Kanäle und Rollen** in **{name}**.\nTippe den genauen Servernamen zum Bestätigen. Kein Zurück.",
  "⚠️ Isto **apaga todos os canais e cargos** de **{name}**.\nEscreve o nome exato do servidor para confirmar. Não há volta.",
  "⚠️ Questo **elimina tutti i canali e i ruoli** di **{name}**.\nScrivi il nome esatto del server per confermare. Non si torna indietro.",
  "⚠️ これは **{name}** の**全チャンネルとロールを削除**します。\n確定するにはサーバー名を正確に入力。取り消し不可。",
  "⚠️ 이 작업은 **{name}**의 **모든 채널과 역할을 삭제**합니다.\n확인하려면 서버 이름을 정확히 입력하세요. 되돌릴 수 없습니다.",
  "⚠️ 这将**删除 {name} 的全部频道和身份组**。\n输入服务器全名确认。无法撤销。")
A("⚠️ Initiating Raid Simulation ({amount} messages)...", "⚠️ Iniciando simulacro de raid ({amount} mensajes)…", "⚠️ Initiating Raid Simulation ({amount} messages)...", "⚠️ Lancement de la simulation de raid ({amount} messages)…", "⚠️ Starte Raid-Simulation ({amount} Nachrichten)…", "⚠️ A iniciar simulacro de raid ({amount} mensagens)…", "⚠️ Avvio simulazione raid ({amount} messaggi)…", "⚠️ レイド模擬を開始（{amount} 件）…", "⚠️ 레이드 시뮬레이션 시작({amount}개 메시지)…", "⚠️ 正在开始突袭模拟（{amount} 条消息）…")
A("⚠️ Note: Some APIs are missing in the .env file.", "⚠️ Faltan algunas APIs en el archivo .env.", "⚠️ Note: Some APIs are missing in the .env file.", "⚠️ Certaines API manquent dans le fichier .env.", "⚠️ Hinweis: Im .env fehlen einige APIs.", "⚠️ Faltam algumas APIs no ficheiro .env.", "⚠️ Mancano alcune API nel file .env.", "⚠️ .env に一部のAPIがありません。", "⚠️ .env 파일에 일부 API가 없습니다.", "⚠️ 注意：.env 中缺少部分 API。")
A("⚠️ Reset Reputation", "⚠️ Reiniciar reputación", "⚠️ Reset Reputation", "⚠️ Réinitialiser la réputation", "⚠️ Reputation zurücksetzen", "⚠️ Reiniciar reputação", "⚠️ Azzera reputazione", "⚠️ 評判をリセット", "⚠️ 평판 초기화", "⚠️ 重置声望")
A("⚠️ Unauthorized Command Attempt", "⚠️ Intento de comando no autorizado", "⚠️ Unauthorized Command Attempt", "⚠️ Tentative de commande non autorisée", "⚠️ Unerlaubter Befehlsversuch", "⚠️ Tentativa de comando não autorizada", "⚠️ Tentativo di comando non autorizzato", "⚠️ 権限のないコマンド試行", "⚠️ 권한 없는 명령 시도", "⚠️ 未授权的命令尝试")
A("⚠️ Warned **{display_name}**. Reason: {reason} (Case #{case_id})", "⚠️ Advertido **{display_name}**. Motivo: {reason} (Caso #{case_id})", "⚠️ Warned **{display_name}**. Reason: {reason} (Case #{case_id})", "⚠️ **{display_name}** averti. Motif : {reason} (Dossier #{case_id})", "⚠️ **{display_name}** verwarnt. Grund: {reason} (Fall #{case_id})", "⚠️ Aviso a **{display_name}**. Motivo: {reason} (Caso #{case_id})", "⚠️ **{display_name}** avvisato. Motivo: {reason} (Caso #{case_id})", "⚠️ **{display_name}** に警告。理由: {reason}（ケース #{case_id}）", "⚠️ **{display_name}**에게 경고. 사유: {reason} (사건 #{case_id})", "⚠️ 已警告 **{display_name}**。原因：{reason}（案件 #{case_id}）")
A("⚠️ Ya tienes un ticket abierto: {mention}", "⚠️ Ya tienes un ticket abierto: {mention}", "⚠️ You already have an open ticket: {mention}", "⚠️ Tu as déjà un ticket ouvert : {mention}", "⚠️ Du hast schon ein offenes Ticket: {mention}", "⚠️ Já tens um ticket aberto: {mention}", "⚠️ Hai già un ticket aperto: {mention}", "⚠️ すでに開いているチケットがあります: {mention}", "⚠️ 이미 열린 티켓이 있습니다: {mention}", "⚠️ 你已有一张未关闭的工单：{mention}")
A("⚠️ Your message in **{name}** was deleted for containing prohibited content.", "⚠️ Tu mensaje en **{name}** se borró por contenido prohibido.", "⚠️ Your message in **{name}** was deleted for containing prohibited content.", "⚠️ Ton message dans **{name}** a été supprimé (contenu interdit).", "⚠️ Deine Nachricht in **{name}** wurde wegen verbotenem Inhalt gelöscht.", "⚠️ A tua mensagem em **{name}** foi apagada por conteúdo proibido.", "⚠️ Il tuo messaggio in **{name}** è stato eliminato per contenuto vietato.", "⚠️ **{name}** のメッセージは禁止コンテンツのため削除されました。", "⚠️ **{name}**의 메시지가 금지된 내용으로 삭제되었습니다.", "⚠️ 你在 **{name}** 的消息因违禁内容被删除。")
A("⚠️ {mention} Stop spamming!", "⚠️ {mention} ¡Deja de spamear!", "⚠️ {mention} Stop spamming!", "⚠️ {mention} arrête le spam !", "⚠️ {mention} hör auf zu spammen!", "⚠️ {mention} para de fazer spam!", "⚠️ {mention} smettila di spammare!", "⚠️ {mention} スパムはやめて！", "⚠️ {mention} 스팸 그만!", "⚠️ {mention} 别刷屏！")
A("⚠️ {mention} Too many mentions!", "⚠️ {mention} ¡Demasiadas menciones!", "⚠️ {mention} Too many mentions!", "⚠️ {mention} trop de mentions !", "⚠️ {mention} zu viele Mentions!", "⚠️ {mention} demasiadas menções!", "⚠️ {mention} troppe menzioni!", "⚠️ {mention} メンションが多すぎます！", "⚠️ {mention} 멘션이 너무 많아요!", "⚠️ {mention} 提及太多！")
A("⚠️ {mention} ese texto distorsionado no está permitido.", "⚠️ {mention} ese texto distorsionado no está permitido.", "⚠️ {mention} that distorted text is not allowed.", "⚠️ {mention} ce texte déformé n'est pas autorisé.", "⚠️ {mention} dieser verzerrte Text ist nicht erlaubt.", "⚠️ {mention} esse texto distorcido não é permitido.", "⚠️ {mention} quel testo distorto non è permesso.", "⚠️ {mention} その歪んだテキストは禁止です。", "⚠️ {mention} 그 왜곡된 텍스트는 허용되지 않습니다.", "⚠️ {mention} 不允许这种变形文字。")
A("⚠️ {mention}, publicar invitaciones de otros servidores no está permitido.", "⚠️ {mention}, publicar invitaciones de otros servidores no está permitido.", "⚠️ {mention}, posting invites to other servers is not allowed.", "⚠️ {mention}, publier des invitations d'autres serveurs n'est pas autorisé.", "⚠️ {mention}, Einladungen anderer Server sind nicht erlaubt.", "⚠️ {mention}, publicar convites de outros servidores não é permitido.", "⚠️ {mention}, pubblicare inviti di altri server non è permesso.", "⚠️ {mention}、他サーバーの招待は禁止です。", "⚠️ {mention}, 다른 서버 초대 게시가 허용되지 않습니다.", "⚠️ {mention}，不允许发布其他服务器邀请。")
A("⚠️ {mention}, you sent a malicious link. The message has been deleted.", "⚠️ {mention}, enviaste un enlace malicioso. El mensaje se ha borrado.", "⚠️ {mention}, you sent a malicious link. The message has been deleted.", "⚠️ {mention}, tu as envoyé un lien malveillant. Message supprimé.", "⚠️ {mention}, du hast einen schädlichen Link gesendet. Nachricht gelöscht.", "⚠️ {mention}, enviaste um link malicioso. A mensagem foi apagada.", "⚠️ {mention}, hai inviato un link dannoso. Messaggio eliminato.", "⚠️ {mention}、悪意あるリンクを送りました。メッセージを削除しました。", "⚠️ {mention}, 악성 링크를 보냈습니다. 메시지를 삭제했습니다.", "⚠️ {mention}，你发送了恶意链接。消息已删除。")
A("⛔ Only the owner can restart the bot.", "⛔ Solo el propietario puede reiniciar el bot.", "⛔ Only the owner can restart the bot.", "⛔ Seul le propriétaire peut redémarrer le bot.", "⛔ Nur der Besitzer darf den Bot neu starten.", "⛔ Só o proprietário pode reiniciar o bot.", "⛔ Solo il proprietario può riavviare il bot.", "⛔ オーナーだけがボットを再起動できます。", "⛔ 소유자만 봇을 재시작할 수 있습니다.", "⛔ 只有所有者可以重启机器人。")
A("⛔ Solo el propietario puede sincronizar comandos.", "⛔ Solo el propietario puede sincronizar comandos.", "⛔ Only the owner can sync commands.", "⛔ Seul le propriétaire peut synchroniser les commandes.", "⛔ Nur der Besitzer darf Befehle synchronisieren.", "⛔ Só o proprietário pode sincronizar comandos.", "⛔ Solo il proprietario può sincronizzare i comandi.", "⛔ オーナーだけがコマンドを同期できます。", "⛔ 소유자만 명령을 동기화할 수 있습니다.", "⛔ 只有所有者可以同步命令。")
A("⛔ Solo el superusuario puede usar `!raid`.", "⛔ Solo el superusuario puede usar `!raid`.", "⛔ Only the superuser can use `!raid`.", "⛔ Seul le superutilisateur peut utiliser `!raid`.", "⛔ Nur der Superuser darf `!raid` nutzen.", "⛔ Só o superutilizador pode usar `!raid`.", "⛔ Solo il superutente può usare `!raid`.", "⛔ スーパーユーザーだけが `!raid` を使えます。", "⛔ 슈퍼유저만 `!raid`를 쓸 수 있습니다.", "⛔ 只有超级用户可以使用 `!raid`。")
A("⛔ This command is restricted to the bot owner only.", "⛔ Este comando es solo para el propietario del bot.", "⛔ This command is restricted to the bot owner only.", "⛔ Cette commande est réservée au propriétaire du bot.", "⛔ Dieser Befehl ist nur für den Bot-Besitzer.", "⛔ Este comando é só para o proprietário do bot.", "⛔ Questo comando è riservato al proprietario del bot.", "⛔ このコマンドはボットオーナー専用です。", "⛔ 이 명령은 봇 소유자 전용입니다.", "⛔ 此命令仅限机器人所有者。")
A("⛔ You are not the owner.", "⛔ No eres el propietario.", "⛔ You are not the owner.", "⛔ Tu n'es pas le propriétaire.", "⛔ Du bist nicht der Besitzer.", "⛔ Não és o proprietário.", "⛔ Non sei il proprietario.", "⛔ オーナーではありません。", "⛔ 소유자가 아닙니다.", "⛔ 你不是所有者。")
A("✅ **System Repair Successful!** Bot has restarted and is stable.", "✅ **¡Reparación del sistema completada!** El bot se ha reiniciado y está estable.", "✅ **System Repair Successful!** Bot has restarted and is stable.", "✅ **Réparation réussie !** Le bot a redémarré et est stable.", "✅ **Systemreparatur erfolgreich!** Der Bot ist neu gestartet und stabil.", "✅ **Reparação concluída!** O bot reiniciou e está estável.", "✅ **Riparazione riuscita!** Il bot è riavviato e stabile.", "✅ **システム修復成功！** ボットは再起動し安定しています。", "✅ **시스템 복구 성공!** 봇이 재시작되었고 안정적입니다.", "✅ **系统修复成功！** 机器人已重启并稳定。")
A("✅ **{name}** logs will now be sent to {mention}.", "✅ Los logs de **{name}** irán a {mention}.", "✅ **{name}** logs will now be sent to {mention}.", "✅ Les journaux **{name}** iront dans {mention}.", "✅ **{name}**-Logs gehen jetzt an {mention}.", "✅ Os logs de **{name}** vão para {mention}.", "✅ I log **{name}** andranno in {mention}.", "✅ **{name}** のログは {mention} に送られます。", "✅ **{name}** 로그가 이제 {mention}(으)로 갑니다.", "✅ **{name}** 日志将发到 {mention}。")
A("✅ AI moderation disabled.", "✅ Moderación IA desactivada.", "✅ AI moderation disabled.", "✅ Modération IA désactivée.", "✅ KI-Moderation deaktiviert.", "✅ Moderação IA desativada.", "✅ Moderazione IA disattivata.", "✅ AIモデレーションを無効にしました。", "✅ AI 모더레이션이 꺼졌습니다.", "✅ 已关闭 AI 管理。")
A("✅ Achievement announcements reset (will try System/General channel).", "✅ Anuncios de logros restablecidos (se probará el canal System/General).", "✅ Achievement announcements reset (will try System/General channel).", "✅ Annonces de succès réinitialisées (essai du salon System/General).", "✅ Erfolg-Ankündigungen zurückgesetzt (Kanal System/General wird versucht).", "✅ Anúncios de conquistas repostos (tenta-se o canal System/General).", "✅ Annunci obiettivi azzerati (si prova il canale System/General).", "✅ 実績告知をリセット（System/General チャンネルを試します）。", "✅ 업적 알림이 초기화됨(System/General 채널을 시도).", "✅ 成就公告已重置（将尝试 System/General 频道）。")
A("✅ Achievement announcements will be sent to {mention}.", "✅ Los anuncios de logros se enviarán a {mention}.", "✅ Achievement announcements will be sent to {mention}.", "✅ Les annonces de succès iront dans {mention}.", "✅ Erfolg-Ankündigungen gehen an {mention}.", "✅ Os anúncios de conquistas vão para {mention}.", "✅ Gli annunci degli obiettivi andranno in {mention}.", "✅ 実績告知は {mention} に送られます。", "✅ 업적 알림이 {mention}(으)로 갑니다.", "✅ 成就公告将发到 {mention}。")
A("✅ Achievements system has been **{status}**.", "✅ El sistema de logros está **{status}**.", "✅ Achievements system has been **{status}**.", "✅ Le système de succès est **{status}**.", "✅ Das Erfolgsystem ist **{status}**.", "✅ O sistema de conquistas está **{status}**.", "✅ Il sistema di obiettivi è **{status}**.", "✅ 実績システムは **{status}** です。", "✅ 업적 시스템이 **{status}**입니다.", "✅ 成就系统已**{status}**。")
A("✅ Added button for {mention} to the message.", "✅ Añadido botón de {mention} al mensaje.", "✅ Added button for {mention} to the message.", "✅ Bouton pour {mention} ajouté au message.", "✅ Button für {mention} zur Nachricht hinzugefügt.", "✅ Botão de {mention} adicionado à mensagem.", "✅ Pulsante per {mention} aggiunto al messaggio.", "✅ {mention} のボタンをメッセージに追加しました。", "✅ {mention} 버튼을 메시지에 추가했습니다.", "✅ 已在消息上为 {mention} 添加按钮。")
A("✅ Added command `{trigger}`.", "✅ Añadido el comando `{trigger}`.", "✅ Added command `{trigger}`.", "✅ Commande `{trigger}` ajoutée.", "✅ Befehl `{trigger}` hinzugefügt.", "✅ Comando `{trigger}` adicionado.", "✅ Comando `{trigger}` aggiunto.", "✅ コマンド `{trigger}` を追加しました。", "✅ 명령 `{trigger}`을(를) 추가했습니다.", "✅ 已添加命令 `{trigger}`。")
A("✅ Added to queue: **{title}** (#{v1})", "✅ Añadido a la cola: **{title}** (#{v1})", "✅ Added to queue: **{title}** (#{v1})", "✅ Ajouté à la file : **{title}** (#{v1})", "✅ Zur Warteschlange: **{title}** (#{v1})", "✅ Adicionado à fila: **{title}** (#{v1})", "✅ Aggiunto in coda: **{title}** (#{v1})", "✅ キューに追加: **{title}** (#{v1})", "✅ 대기열에 추가: **{title}** (#{v1})", "✅ 已加入队列：**{title}** (#{v1})")
A("✅ All notes deleted.", "✅ Todas las notas borradas.", "✅ All notes deleted.", "✅ Toutes les notes ont été supprimées.", "✅ Alle Notizen gelöscht.", "✅ Todas as notas apagadas.", "✅ Tutte le note eliminate.", "✅ メモをすべて削除しました。", "✅ 모든 메모가 삭제되었습니다.", "✅ 已删除全部备注。")
A("✅ All reputation has been reset.", "✅ Se ha reiniciado toda la reputación.", "✅ All reputation has been reset.", "✅ Toute la réputation a été réinitialisée.", "✅ Die gesamte Reputation wurde zurückgesetzt.", "✅ Toda a reputação foi reiniciada.", "✅ Tutta la reputazione è stata azzerata.", "✅ 評判をすべてリセットしました。", "✅ 모든 평판이 초기화되었습니다.", "✅ 已重置全部声望。")
A("✅ Anti-raid disabled.", "✅ Anti-raid desactivado.", "✅ Anti-raid disabled.", "✅ Anti-raid désactivé.", "✅ Anti-Raid deaktiviert.", "✅ Anti-raid desativado.", "✅ Anti-raid disattivato.", "✅ アンチレイドを無効にしました。", "✅ 안티레이드가 꺼졌습니다.", "✅ 已关闭反突袭。")
A("✅ Auto-response added!\n**Trigger:** `{trigger}`\n**Response:** {response}", "✅ Autorespuesta añadida.\n**Activador:** `{trigger}`\n**Respuesta:** {response}", "✅ Auto-response added!\n**Trigger:** `{trigger}`\n**Response:** {response}", "✅ Réponse auto ajoutée.\n**Déclencheur :** `{trigger}`\n**Réponse :** {response}", "✅ Auto-Antwort hinzugefügt.\n**Auslöser:** `{trigger}`\n**Antwort:** {response}", "✅ Autoresposta adicionada.\n**Gatilho:** `{trigger}`\n**Resposta:** {response}", "✅ Autorisposta aggiunta.\n**Trigger:** `{trigger}`\n**Risposta:** {response}", "✅ 自動応答を追加しました。\n**トリガー:** `{trigger}`\n**応答:** {response}", "✅ 자동 응답이 추가되었습니다.\n**트리거:** `{trigger}`\n**응답:** {response}", "✅ 已添加自动回复。\n**触发词：** `{trigger}`\n**回复：** {response}")
A("✅ Bienvenidas **{status}** en {mention}.\nMensaje: `{v2}`", "✅ Bienvenidas **{status}** en {mention}.\nMensaje: `{v2}`", "✅ Welcome **{status}** in {mention}.\nMessage: `{v2}`", "✅ Bienvenues **{status}** dans {mention}.\nMessage : `{v2}`", "✅ Willkommen **{status}** in {mention}.\nNachricht: `{v2}`", "✅ Boas-vindas **{status}** em {mention}.\nMensagem: `{v2}`", "✅ Benvenuti **{status}** in {mention}.\nMessaggio: `{v2}`", "✅ 歓迎は {mention} で **{status}**。\nメッセージ: `{v2}`", "✅ 환영이 {mention}에서 **{status}**입니다.\n메시지: `{v2}`", "✅ 欢迎在 {mention} **{status}**。\n消息：`{v2}`")
A("✅ Birthday announcements will be sent to {mention}", "✅ Los anuncios de cumpleaños irán a {mention}", "✅ Birthday announcements will be sent to {mention}", "✅ Les annonces d'anniversaire iront dans {mention}", "✅ Geburtstagsankündigungen gehen an {mention}", "✅ Os anúncios de aniversário vão para {mention}", "✅ Gli annunci di compleanno andranno in {mention}", "✅ 誕生日告知は {mention} に送られます", "✅ 생일 알림이 {mention}(으)로 갑니다", "✅ 生日公告将发到 {mention}")
A("✅ Birthday removed.", "✅ Cumpleaños eliminado.", "✅ Birthday removed.", "✅ Anniversaire retiré.", "✅ Geburtstag entfernt.", "✅ Aniversário removido.", "✅ Compleanno rimosso.", "✅ 誕生日を削除しました。", "✅ 생일이 삭제되었습니다.", "✅ 已移除生日。")

