from _rest import add as A

A("✅ Welcome Message Updated",
  "✅ Mensaje de bienvenida actualizado",
  "✅ Welcome Message Updated",
  "✅ Message de bienvenue mis à jour",
  "✅ Willkommensnachricht aktualisiert",
  "✅ Mensagem de boas-vindas atualizada",
  "✅ Messaggio di benvenuto aggiornato",
  "✅ 歓迎メッセージを更新しました",
  "✅ 환영 메시지가 업데이트됨",
  "✅ 已更新欢迎消息")
A("✅ Ya estás verificado en este servidor.",
  "✅ Ya estás verificado en este servidor.",
  "✅ You are already verified in this server.",
  "✅ Tu es déjà vérifié sur ce serveur.",
  "✅ Du bist auf diesem Server bereits verifiziert.",
  "✅ Já estás verificado neste servidor.",
  "✅ Sei già verificato in questo server.",
  "✅ このサーバーではすでに認証済みです。",
  "✅ 이 서버에서 이미 인증되어 있습니다.",
  "✅ 你已在此服务器完成验证。")
A("✅ You've entered the giveaway for **{prize}**! Good luck! 🍀",
  "✅ Has entrado al sorteo de **{prize}**. ¡Suerte! 🍀",
  "✅ You've entered the giveaway for **{prize}**! Good luck! 🍀",
  "✅ Tu es inscrit au giveaway de **{prize}** ! Bonne chance ! 🍀",
  "✅ Du nimmst am Giveaway für **{prize}** teil! Viel Glück! 🍀",
  "✅ Entraste no sorteio de **{prize}**! Boa sorte! 🍀",
  "✅ Sei iscritto al giveaway di **{prize}**! In bocca al lupo! 🍀",
  "✅ **{prize}** のギブアウェイに参加しました！頑張って！🍀",
  "✅ **{prize}** 기브어웨이에 참여했습니다! 행운을 빌어요! 🍀",
  "✅ 你已参加 **{prize}** 抽奖！祝你好运！🍀")
A("✅ You've left the giveaway.",
  "✅ Has salido del sorteo.",
  "✅ You've left the giveaway.",
  "✅ Tu as quitté le giveaway.",
  "✅ Du hast das Giveaway verlassen.",
  "✅ Saíste do sorteio.",
  "✅ Hai lasciato il giveaway.",
  "✅ ギブアウェイから退出しました。",
  "✅ 기브어웨이에서 나갔습니다.",
  "✅ 你已退出抽奖。")
A("✅ Your suggestion has been submitted!",
  "✅ ¡Tu sugerencia ha sido enviada!",
  "✅ Your suggestion has been submitted!",
  "✅ Ta suggestion a été envoyée !",
  "✅ Dein Vorschlag wurde eingereicht!",
  "✅ A tua sugestão foi enviada!",
  "✅ Il tuo suggerimento è stato inviato!",
  "✅ 提案を送信しました！",
  "✅ 제안이 제출되었습니다!",
  "✅ 你的建议已提交！")
A("✅ {mention} has been blacklisted. Reason: {reason}",
  "✅ {mention} ha sido añadido a la lista negra. Motivo: {reason}",
  "✅ {mention} has been blacklisted. Reason: {reason}",
  "✅ {mention} a été ajouté à la liste noire. Raison : {reason}",
  "✅ {mention} wurde auf die Blacklist gesetzt. Grund: {reason}",
  "✅ {mention} foi colocado na lista negra. Motivo: {reason}",
  "✅ {mention} è stato messo in blacklist. Motivo: {reason}",
  "✅ {mention} をブラックリストに追加しました。理由: {reason}",
  "✅ {mention}이(가) 블랙리스트에 추가됨. 사유: {reason}",
  "✅ {mention} 已加入黑名单。原因：{reason}")
A("✅ {mention} has been permitted to join.",
  "✅ {mention} tiene permiso para unirse.",
  "✅ {mention} has been permitted to join.",
  "✅ {mention} est autorisé à rejoindre.",
  "✅ {mention} darf beitreten.",
  "✅ {mention} tem permissão para entrar.",
  "✅ {mention} è autorizzato a entrare.",
  "✅ {mention} の参加を許可しました。",
  "✅ {mention}의 참가가 허용되었습니다.",
  "✅ 已允许 {mention} 加入。")
A("✅ {mention} has been removed from the blacklist.",
  "✅ {mention} ha sido quitado de la lista negra.",
  "✅ {mention} has been removed from the blacklist.",
  "✅ {mention} a été retiré de la liste noire.",
  "✅ {mention} wurde von der Blacklist entfernt.",
  "✅ {mention} foi removido da lista negra.",
  "✅ {mention} è stato rimosso dalla blacklist.",
  "✅ {mention} をブラックリストから外しました。",
  "✅ {mention}이(가) 블랙리스트에서 제거됨.",
  "✅ 已将 {mention} 移出黑名单。")
A("✅ {mention} verificado **solo en {name}** (`{id}`). No aplica a otros servidores.",
  "✅ {mention} verificado **solo en {name}** (`{id}`). No aplica a otros servidores.",
  "✅ {mention} verified **only in {name}** (`{id}`). Does not apply to other servers.",
  "✅ {mention} vérifié **uniquement sur {name}** (`{id}`). Ça ne s'applique pas aux autres serveurs.",
  "✅ {mention} nur **auf {name}** verifiziert (`{id}`). Gilt nicht für andere Server.",
  "✅ {mention} verificado **só em {name}** (`{id}`). Não se aplica a outros servidores.",
  "✅ {mention} verificato **solo in {name}** (`{id}`). Non vale per gli altri server.",
  "✅ {mention} は **{name}** のみ認証 (`{id}`)。他サーバーには適用されません。",
  "✅ {mention}은(는) **{name}**에서만 인증됨 (`{id}`). 다른 서버에는 적용되지 않습니다.",
  "✅ {mention} 仅在 **{name}** 验证（`{id}`）。不影响其他服务器。")
A("✅ ¡Embed enviado con éxito a {mention}!",
  "✅ ¡Embed enviado con éxito a {mention}!",
  "✅ Embed sent successfully to {mention}!",
  "✅ Embed envoyé avec succès dans {mention} !",
  "✅ Embed erfolgreich an {mention} gesendet!",
  "✅ Embed enviado com sucesso para {mention}!",
  "✅ Embed inviato con successo in {mention}!",
  "✅ 埋め込みを {mention} に送信しました！",
  "✅ 임베드를 {mention}에 보냈습니다!",
  "✅ 已成功将嵌入消息发送到 {mention}！")
A("✅ ¡Verificación completada! Ya tienes acceso.\nOpcional: registra tu navegador para que el staff pueda detectar multicuentas.",
  "✅ ¡Verificación completada! Ya tienes acceso.\nOpcional: registra tu navegador para que el staff pueda detectar multicuentas.",
  "✅ Verification complete! You now have access.\nOptional: register your browser so staff can detect multi-accounts.",
  "✅ Vérification terminée ! Tu as maintenant accès.\nOptionnel : enregistre ton navigateur pour que le staff détecte les multi-comptes.",
  "✅ Verifizierung abgeschlossen! Du hast jetzt Zugriff.\nOptional: registriere deinen Browser, damit das Team Mehrfachaccounts erkennt.",
  "✅ Verificação concluída! Já tens acesso.\nOpcional: regista o teu navegador para o staff detetar multicontas.",
  "✅ Verifica completata! Ora hai accesso.\nOpzionale: registra il browser così lo staff può rilevare i multi-account.",
  "✅ 認証完了！アクセスできるようになりました。\n任意: ブラウザを登録するとスタッフが複数アカウントを検出できます。",
  "✅ 인증 완료! 이제 접근할 수 있습니다.\n선택: 브라우저를 등록하면 스태프가 다중 계정을 감지할 수 있습니다.",
  "✅ 验证完成！你已获得访问权限。\n可选：登记浏览器，便于管理组检测多账号。")
A("✋ **{display_name}** (`{id}`) ha reclamado el ticket.",
  "✋ **{display_name}** (`{id}`) ha reclamado el ticket.",
  "✋ **{display_name}** (`{id}`) claimed the ticket.",
  "✋ **{display_name}** (`{id}`) a pris en charge le ticket.",
  "✋ **{display_name}** (`{id}`) hat das Ticket übernommen.",
  "✋ **{display_name}** (`{id}`) reclamou o ticket.",
  "✋ **{display_name}** (`{id}`) ha preso in carico il ticket.",
  "✋ **{display_name}** (`{id}`) がチケットを担当しました。",
  "✋ **{display_name}** (`{id}`)이(가) 티켓을 맡았습니다.",
  "✋ **{display_name}** (`{id}`) 已认领该工单。")
A("✋ {mention} ha reclamado este ticket.",
  "✋ {mention} ha reclamado este ticket.",
  "✋ {mention} claimed this ticket.",
  "✋ {mention} a pris en charge ce ticket.",
  "✋ {mention} hat dieses Ticket übernommen.",
  "✋ {mention} reclamou este ticket.",
  "✋ {mention} ha preso in carico questo ticket.",
  "✋ {mention} がこのチケットを担当しました。",
  "✋ {mention}이(가) 이 티켓을 맡았습니다.",
  "✋ {mention} 已认领此工单。")
A("✏️ Channel renamed to **{name}**.",
  "✏️ Canal renombrado a **{name}**.",
  "✏️ Channel renamed to **{name}**.",
  "✏️ Salon renommé en **{name}**.",
  "✏️ Kanal umbenannt in **{name}**.",
  "✏️ Canal mudado para **{name}**.",
  "✏️ Canale rinominato in **{name}**.",
  "✏️ チャンネル名を **{name}** に変更。",
  "✏️ 채널 이름이 **{name}**(으)로 변경됨.",
  "✏️ 频道已重命名为 **{name}**。")
A("✏️ Channel renamed to **{new_name}**!",
  "✏️ ¡Canal renombrado a **{new_name}**!",
  "✏️ Channel renamed to **{new_name}**!",
  "✏️ Salon renommé en **{new_name}** !",
  "✏️ Kanal umbenannt in **{new_name}**!",
  "✏️ Canal mudado para **{new_name}**!",
  "✏️ Canale rinominato in **{new_name}**!",
  "✏️ チャンネル名を **{new_name}** に変更！",
  "✏️ 채널 이름이 **{new_name}**(으)로 변경됨!",
  "✏️ 频道已重命名为 **{new_name}**！")
A("✨ Reputation Given!",
  "✨ ¡Reputación otorgada!",
  "✨ Reputation Given!",
  "✨ Réputation donnée !",
  "✨ Ruf vergeben!",
  "✨ Reputação atribuída!",
  "✨ Reputazione assegnata!",
  "✨ 評価を送りました！",
  "✨ 평판을 줬습니다!",
  "✨ 已给予声望！")
A("✨ Servidores Premium",
  "✨ Servidores Premium",
  "✨ Premium servers",
  "✨ Serveurs Premium",
  "✨ Premium-Server",
  "✨ Servidores Premium",
  "✨ Server Premium",
  "✨ Premiumサーバー",
  "✨ 프리미엄 서버",
  "✨ Premium 服务器")
A("❌ **ACCESS DENIED**: This command is restricted to the Super Owner.",
  "❌ **ACCESO DENEGADO**: este comando es solo para el Super Owner.",
  "❌ **ACCESS DENIED**: This command is restricted to the Super Owner.",
  "❌ **ACCÈS REFUSÉ** : cette commande est réservée au Super Owner.",
  "❌ **ZUGRIFF VERWEIGERT**: Dieser Befehl ist dem Super Owner vorbehalten.",
  "❌ **ACESSO NEGADO**: este comando é só para o Super Owner.",
  "❌ **ACCESSO NEGATO**: questo comando è riservato al Super Owner.",
  "❌ **アクセス拒否**: このコマンドは Super Owner 専用です。",
  "❌ **접근 거부**: 이 명령은 Super Owner 전용입니다.",
  "❌ **拒绝访问**：此命令仅限 Super Owner。")
A("❌ **{v0}** is not a recognized word. Try again!",
  "❌ **{v0}** no es una palabra reconocida. ¡Inténtalo de nuevo!",
  "❌ **{v0}** is not a recognized word. Try again!",
  "❌ **{v0}** n'est pas un mot reconnu. Réessaie !",
  "❌ **{v0}** ist kein erkanntes Wort. Versuch's nochmal!",
  "❌ **{v0}** não é uma palavra reconhecida. Tenta outra vez!",
  "❌ **{v0}** non è una parola riconosciuta. Riprova!",
  "❌ **{v0}** は認識できない単語です。もう一度！",
  "❌ **{v0}**은(는) 인식된 단어가 아닙니다. 다시 시도하세요!",
  "❌ **{v0}** 不是已识别的单词。请再试！")
A("❌ A game is active here.",
  "❌ Ya hay una partida activa aquí.",
  "❌ A game is active here.",
  "❌ Une partie est déjà en cours ici.",
  "❌ Hier läuft bereits ein Spiel.",
  "❌ Já há um jogo ativo aqui.",
  "❌ C'è già una partita attiva qui.",
  "❌ ここではゲームが進行中です。",
  "❌ 여기에서 게임이 진행 중입니다.",
  "❌ 这里已有进行中的游戏。")
A("❌ A game is already active in this channel!",
  "❌ ¡Ya hay una partida activa en este canal!",
  "❌ A game is already active in this channel!",
  "❌ Une partie est déjà en cours dans ce salon !",
  "❌ In diesem Kanal läuft bereits ein Spiel!",
  "❌ Já há um jogo ativo neste canal!",
  "❌ C'è già una partita attiva in questo canale!",
  "❌ このチャンネルではすでにゲーム中です！",
  "❌ 이 채널에서 이미 게임이 진행 중입니다!",
  "❌ 此频道已有进行中的游戏！")
A("❌ AI service unavailable.",
  "❌ Servicio de IA no disponible.",
  "❌ AI service unavailable.",
  "❌ Service d'IA indisponible.",
  "❌ KI-Dienst nicht verfügbar.",
  "❌ Serviço de IA indisponível.",
  "❌ Servizio IA non disponibile.",
  "❌ AIサービスは利用できません。",
  "❌ AI 서비스를 사용할 수 없습니다.",
  "❌ AI 服务不可用。")
A("❌ AI service unavailable. Make sure the Chatbot cog is loaded.",
  "❌ Servicio de IA no disponible. Asegúrate de que el cog Chatbot esté cargado.",
  "❌ AI service unavailable. Make sure the Chatbot cog is loaded.",
  "❌ Service d'IA indisponible. Vérifie que le cog Chatbot est chargé.",
  "❌ KI-Dienst nicht verfügbar. Stelle sicher, dass das Chatbot-Cog geladen ist.",
  "❌ Serviço de IA indisponível. Confirma que o cog Chatbot está carregado.",
  "❌ Servizio IA non disponibile. Assicurati che il cog Chatbot sia caricato.",
  "❌ AIサービスは利用できません。Chatbot cog が読み込まれているか確認してください。",
  "❌ AI 서비스를 사용할 수 없습니다. Chatbot cog가 로드되었는지 확인하세요.",
  "❌ AI 服务不可用。请确认已加载 Chatbot cog。")
A("❌ Achievement '{achievement_name}' not found!",
  "❌ No se encontró el logro '{achievement_name}'.",
  "❌ Achievement '{achievement_name}' not found!",
  "❌ Succès '{achievement_name}' introuvable !",
  "❌ Erfolg '{achievement_name}' nicht gefunden!",
  "❌ Conquista '{achievement_name}' não encontrada!",
  "❌ Obiettivo '{achievement_name}' non trovato!",
  "❌ 実績 '{achievement_name}' が見つかりません！",
  "❌ 업적 '{achievement_name}'을(를) 찾을 수 없습니다!",
  "❌ 未找到成就 '{achievement_name}'！")
A("❌ Adjunto inválido. Por favor sube un archivo de imagen.",
  "❌ Adjunto inválido. Por favor sube un archivo de imagen.",
  "❌ Invalid attachment. Please upload an image file.",
  "❌ Pièce jointe invalide. Envoie un fichier image.",
  "❌ Ungültiger Anhang. Lade eine Bilddatei hoch.",
  "❌ Anexo inválido. Envia um ficheiro de imagem.",
  "❌ Allegato non valido. Carica un file immagine.",
  "❌ 添付が無効です。画像ファイルをアップロードしてください。",
  "❌ 잘못된 첨부입니다. 이미지 파일을 올려 주세요.",
  "❌ 附件无效。请上传图片文件。")
A("❌ Advanced stats are not available (matplotlib not installed).",
  "❌ Las stats avanzadas no están disponibles (matplotlib no instalado).",
  "❌ Advanced stats are not available (matplotlib not installed).",
  "❌ Stats avancées indisponibles (matplotlib non installé).",
  "❌ Erweiterte Stats nicht verfügbar (matplotlib nicht installiert).",
  "❌ Stats avançadas indisponíveis (matplotlib não instalado).",
  "❌ Statistiche avanzate non disponibili (matplotlib non installato).",
  "❌ 高度な統計は利用できません（matplotlib 未インストール）。",
  "❌ 고급 통계를 사용할 수 없습니다(matplotlib 미설치).",
  "❌ 高级统计不可用（未安装 matplotlib）。")
A("❌ An error occurred: {e}",
  "❌ Ha ocurrido un error: {e}",
  "❌ An error occurred: {e}",
  "❌ Une erreur s'est produite : {e}",
  "❌ Ein Fehler ist aufgetreten: {e}",
  "❌ Ocorreu um erro: {e}",
  "❌ Si è verificato un errore: {e}",
  "❌ エラーが発生しました: {e}",
  "❌ 오류가 발생했습니다: {e}",
  "❌ 发生错误：{e}")
A("❌ An error occurred: {v0}",
  "❌ Ha ocurrido un error: {v0}",
  "❌ An error occurred: {v0}",
  "❌ Une erreur s'est produite : {v0}",
  "❌ Ein Fehler ist aufgetreten: {v0}",
  "❌ Ocorreu um erro: {v0}",
  "❌ Si è verificato un errore: {v0}",
  "❌ エラーが発生しました: {v0}",
  "❌ 오류가 발생했습니다: {v0}",
  "❌ 发生错误：{v0}")
A("❌ An unexpected error occurred: {e}",
  "❌ Ha ocurrido un error inesperado: {e}",
  "❌ An unexpected error occurred: {e}",
  "❌ Une erreur inattendue s'est produite : {e}",
  "❌ Ein unerwarteter Fehler ist aufgetreten: {e}",
  "❌ Ocorreu um erro inesperado: {e}",
  "❌ Si è verificato un errore imprevisto: {e}",
  "❌ 予期しないエラーが発生しました: {e}",
  "❌ 예기치 않은 오류가 발생했습니다: {e}",
  "❌ 发生意外错误：{e}")
A("❌ Anti-raid not configured. Use `/antiraid setup`.",
  "❌ Anti-raid no configurado. Usa `/antiraid setup`.",
  "❌ Anti-raid not configured. Use `/antiraid setup`.",
  "❌ Anti-raid non configuré. Utilise `/antiraid setup`.",
  "❌ Anti-Raid nicht konfiguriert. Nutze `/antiraid setup`.",
  "❌ Anti-raid não configurado. Usa `/antiraid setup`.",
  "❌ Anti-raid non configurato. Usa `/antiraid setup`.",
  "❌ アンチレイド未設定です。`/antiraid setup` を使ってください。",
  "❌ 안티레이드가 설정되지 않았습니다. `/antiraid setup`을 사용하세요.",
  "❌ 未配置防突袭。请使用 `/antiraid setup`。")
A("❌ Añade al menos un rol válido (sin admin).",
  "❌ Añade al menos un rol válido (sin admin).",
  "❌ Add at least one valid role (no admin).",
  "❌ Ajoute au moins un rôle valide (sans admin).",
  "❌ Füge mindestens eine gültige Rolle hinzu (ohne Admin).",
  "❌ Adiciona pelo menos um cargo válido (sem admin).",
  "❌ Aggiungi almeno un ruolo valido (senza admin).",
  "❌ 有効なロールを1つ以上追加してください（管理者なし）。",
  "❌ 유효한 역할을 하나 이상 추가하세요(관리자 제외).",
  "❌ 请至少添加一个有效身份组（不含管理员）。")
A("❌ Backup file is too large (max 5MB).",
  "❌ El archivo de backup es demasiado grande (máx. 5 MB).",
  "❌ Backup file is too large (max 5MB).",
  "❌ Le fichier de sauvegarde est trop volumineux (max 5 Mo).",
  "❌ Die Backup-Datei ist zu groß (max. 5 MB).",
  "❌ O ficheiro de backup é demasiado grande (máx. 5 MB).",
  "❌ Il file di backup è troppo grande (max 5 MB).",
  "❌ バックアップファイルが大きすぎます（最大 5MB）。",
  "❌ 백업 파일이 너무 큽니다(최대 5MB).",
  "❌ 备份文件太大（最大 5MB）。")
A("❌ Button for that role not found on the message.",
  "❌ No se encontró el botón de ese rol en el mensaje.",
  "❌ Button for that role not found on the message.",
  "❌ Bouton pour ce rôle introuvable sur le message.",
  "❌ Button für diese Rolle auf der Nachricht nicht gefunden.",
  "❌ Botão desse cargo não encontrado na mensagem.",
  "❌ Pulsante per quel ruolo non trovato nel messaggio.",
  "❌ そのロールのボタンがメッセージ上にありません。",
  "❌ 해당 역할 버튼을 메시지에서 찾지 못했습니다.",
  "❌ 消息上找不到该身份组的按钮。")
A("❌ Cannot scan private, internal, or reserved IP addresses.",
  "❌ No se pueden escanear IPs privadas, internas o reservadas.",
  "❌ Cannot scan private, internal, or reserved IP addresses.",
  "❌ Impossible de scanner des IP privées, internes ou réservées.",
  "❌ Private, interne oder reservierte IPs können nicht gescannt werden.",
  "❌ Não é possível analisar IPs privadas, internas ou reservadas.",
  "❌ Impossibile scansionare IP private, interne o riservate.",
  "❌ プライベート・内部・予約済み IP はスキャンできません。",
  "❌ 사설, 내부 또는 예약 IP는 검사할 수 없습니다.",
  "❌ 无法扫描私有、内部或保留 IP 地址。")
A("❌ Case #{case_id} not found in this server.",
  "❌ Caso #{case_id} no encontrado en este servidor.",
  "❌ Case #{case_id} not found in this server.",
  "❌ Dossier #{case_id} introuvable sur ce serveur.",
  "❌ Fall #{case_id} auf diesem Server nicht gefunden.",
  "❌ Caso #{case_id} não encontrado neste servidor.",
  "❌ Caso #{case_id} non trovato in questo server.",
  "❌ このサーバーにケース #{case_id} はありません。",
  "❌ 이 서버에서 사건 #{case_id}을(를) 찾을 수 없습니다.",
  "❌ 此服务器找不到案件 #{case_id}。")
A("❌ Case not found.",
  "❌ Caso no encontrado.",
  "❌ Case not found.",
  "❌ Dossier introuvable.",
  "❌ Fall nicht gefunden.",
  "❌ Caso não encontrado.",
  "❌ Caso non trovato.",
  "❌ ケースが見つかりません。",
  "❌ 사건을 찾을 수 없습니다.",
  "❌ 未找到案件。")
A("❌ Categoría no válida. Usa el prefijo en un canal marcado como NSFW.",
  "❌ Categoría no válida. Usa el prefijo en un canal marcado como NSFW.",
  "❌ Invalid category. Use the prefix in a channel marked NSFW.",
  "❌ Catégorie invalide. Utilise le préfixe dans un salon marqué NSFW.",
  "❌ Ungültige Kategorie. Nutze das Präfix in einem als NSFW markierten Kanal.",
  "❌ Categoria inválida. Usa o prefixo num canal marcado como NSFW.",
  "❌ Categoria non valida. Usa il prefisso in un canale contrassegnato NSFW.",
  "❌ 無効なカテゴリです。NSFW チャンネルでプレフィックスを使ってください。",
  "❌ 유효하지 않은 카테고리입니다. NSFW로 표시된 채널에서 접두사를 사용하세요.",
  "❌ 分类无效。请在标记为 NSFW 的频道使用前缀。")
A("❌ Channel not found.",
  "❌ Canal no encontrado.",
  "❌ Channel not found.",
  "❌ Salon introuvable.",
  "❌ Kanal nicht gefunden.",
  "❌ Canal não encontrado.",
  "❌ Canale non trovato.",
  "❌ チャンネルが見つかりません。",
  "❌ 채널을 찾을 수 없습니다.",
  "❌ 未找到频道。")
A("❌ Choose a horse between 1 and 5!",
  "❌ ¡Elige un caballo entre 1 y 5!",
  "❌ Choose a horse between 1 and 5!",
  "❌ Choisis un cheval entre 1 et 5 !",
  "❌ Wähle ein Pferd zwischen 1 und 5!",
  "❌ Escolhe um cavalo entre 1 e 5!",
  "❌ Scegli un cavallo tra 1 e 5!",
  "❌ 1〜5 の馬を選んでください！",
  "❌ 1에서 5 사이의 말을 고르세요!",
  "❌ 请选择 1 到 5 号马！")
A("❌ Command `{trigger}` already exists.",
  "❌ El comando `{trigger}` ya existe.",
  "❌ Command `{trigger}` already exists.",
  "❌ La commande `{trigger}` existe déjà.",
  "❌ Befehl `{trigger}` existiert bereits.",
  "❌ O comando `{trigger}` já existe.",
  "❌ Il comando `{trigger}` esiste già.",
  "❌ コマンド `{trigger}` は既にあります。",
  "❌ 명령 `{trigger}`이(가) 이미 있습니다.",
  "❌ 命令 `{trigger}` 已存在。")
A("❌ Command `{trigger}` not found.",
  "❌ Comando `{trigger}` no encontrado.",
  "❌ Command `{trigger}` not found.",
  "❌ Commande `{trigger}` introuvable.",
  "❌ Befehl `{trigger}` nicht gefunden.",
  "❌ Comando `{trigger}` não encontrado.",
  "❌ Comando `{trigger}` non trovato.",
  "❌ コマンド `{trigger}` が見つかりません。",
  "❌ 명령 `{trigger}`을(를) 찾을 수 없습니다.",
  "❌ 未找到命令 `{trigger}`。")
A("❌ Configura `/verification setup` primero.",
  "❌ Configura `/verification setup` primero.",
  "❌ Configure `/verification setup` first.",
  "❌ Configure `/verification setup` d'abord.",
  "❌ Richte zuerst `/verification setup` ein.",
  "❌ Configura `/verification setup` primeiro.",
  "❌ Configura prima `/verification setup`.",
  "❌ 先に `/verification setup` を設定してください。",
  "❌ 먼저 `/verification setup`을 설정하세요.",
  "❌ 请先配置 `/verification setup`。")
A("❌ Could not fetch image.",
  "❌ No se pudo obtener la imagen.",
  "❌ Could not fetch image.",
  "❌ Impossible de récupérer l'image.",
  "❌ Bild konnte nicht geladen werden.",
  "❌ Não foi possível obter a imagem.",
  "❌ Impossibile recuperare l'immagine.",
  "❌ 画像を取得できませんでした。",
  "❌ 이미지를 가져오지 못했습니다.",
  "❌ 无法获取图片。")
A("❌ Could not fetch image. Try again later.",
  "❌ No se pudo obtener la imagen. Inténtalo más tarde.",
  "❌ Could not fetch image. Try again later.",
  "❌ Impossible de récupérer l'image. Réessaie plus tard.",
  "❌ Bild konnte nicht geladen werden. Versuch's später nochmal.",
  "❌ Não foi possível obter a imagem. Tenta mais tarde.",
  "❌ Impossibile recuperare l'immagine. Riprova più tardi.",
  "❌ 画像を取得できませんでした。後でもう一度。",
  "❌ 이미지를 가져오지 못했습니다. 나중에 다시 시도하세요.",
  "❌ 无法获取图片。请稍后再试。")
A("❌ Could not retrieve price for `{v0}`.",
  "❌ No se pudo obtener el precio de `{v0}`.",
  "❌ Could not retrieve price for `{v0}`.",
  "❌ Impossible de récupérer le prix de `{v0}`.",
  "❌ Preis für `{v0}` konnte nicht geladen werden.",
  "❌ Não foi possível obter o preço de `{v0}`.",
  "❌ Impossibile recuperare il prezzo di `{v0}`.",
  "❌ `{v0}` の価格を取得できませんでした。",
  "❌ `{v0}`의 가격을 가져오지 못했습니다.",
  "❌ 无法获取 `{v0}` 的价格。")
A("❌ Could not save the avatar: {exc}",
  "❌ No se pudo guardar el avatar: {exc}",
  "❌ Could not save the avatar: {exc}",
  "❌ Impossible d'enregistrer l'avatar : {exc}",
  "❌ Avatar konnte nicht gespeichert werden: {exc}",
  "❌ Não foi possível guardar o avatar: {exc}",
  "❌ Impossibile salvare l'avatar: {exc}",
  "❌ アバターを保存できませんでした: {exc}",
  "❌ 아바타를 저장하지 못했습니다: {exc}",
  "❌ 无法保存头像：{exc}")
A("❌ Could not save the image: {exc}",
  "❌ No se pudo guardar la imagen: {exc}",
  "❌ Could not save the image: {exc}",
  "❌ Impossible d'enregistrer l'image : {exc}",
  "❌ Bild konnte nicht gespeichert werden: {exc}",
  "❌ Não foi possível guardar a imagem: {exc}",
  "❌ Impossibile salvare l'immagine: {exc}",
  "❌ 画像を保存できませんでした: {exc}",
  "❌ 이미지를 저장하지 못했습니다: {exc}",
  "❌ 无法保存图片：{exc}")
