from _rest import add as A

A("✅ Cada verificación de este servidor se registrará en {mention} (navegador, reto, staff). El listado completo está en {DASHBOARD_URL}/dashboard.",
  "✅ Cada verificación de este servidor se registrará en {mention} (navegador, reto, staff). El listado completo está en {DASHBOARD_URL}/dashboard.",
  "✅ Every verification in this server will be logged in {mention} (browser, challenge, staff). The full list is at {DASHBOARD_URL}/dashboard.",
  "✅ Chaque vérification de ce serveur ira dans {mention} (navigateur, défi, staff). La liste complète est sur {DASHBOARD_URL}/dashboard.",
  "✅ Jede Verifizierung dieses Servers landet in {mention} (Browser, Challenge, Staff). Die volle Liste: {DASHBOARD_URL}/dashboard.",
  "✅ Cada verificação deste servidor ficará em {mention} (navegador, desafio, staff). A lista completa está em {DASHBOARD_URL}/dashboard.",
  "✅ Ogni verifica di questo server andrà in {mention} (browser, sfida, staff). L'elenco completo è su {DASHBOARD_URL}/dashboard.",
  "✅ このサーバーの認証は {mention} に記録されます（ブラウザ、チャレンジ、スタッフ）。一覧は {DASHBOARD_URL}/dashboard。",
  "✅ 이 서버의 모든 인증이 {mention}에 기록됩니다(브라우저, 도전, 스태프). 전체 목록: {DASHBOARD_URL}/dashboard.",
  "✅ 此服务器的每次验证都会记入 {mention}（浏览器、挑战、管理组）。完整列表在 {DASHBOARD_URL}/dashboard。")
A("✅ Canal de stats: {mention} · zona `{tz_name}`", "✅ Canal de stats: {mention} · zona `{tz_name}`", "✅ Stats channel: {mention} · zone `{tz_name}`", "✅ Salon de stats : {mention} · fuseau `{tz_name}`", "✅ Statistikkanal: {mention} · Zone `{tz_name}`", "✅ Canal de stats: {mention} · fuso `{tz_name}`", "✅ Canale stats: {mention} · fuso `{tz_name}`", "✅ 統計チャンネル: {mention} · ゾーン `{tz_name}`", "✅ 통계 채널: {mention} · 시간대 `{tz_name}`", "✅ 统计频道：{mention} · 时区 `{tz_name}`")
A("✅ Cancelled scheduled message `{message_id}`.", "✅ Cancelado el mensaje programado `{message_id}`.", "✅ Cancelled scheduled message `{message_id}`.", "✅ Message programmé `{message_id}` annulé.", "✅ Geplante Nachricht `{message_id}` abgebrochen.", "✅ Mensagem programada `{message_id}` cancelada.", "✅ Messaggio programmato `{message_id}` annullato.", "✅ 予約メッセージ `{message_id}` をキャンセルしました。", "✅ 예약 메시지 `{message_id}`을(를) 취소했습니다.", "✅ 已取消定时消息 `{message_id}`。")
A("✅ Categoría **{nombre}** eliminada. Publica de nuevo `/ticket panel`.", "✅ Categoría **{nombre}** eliminada. Publica de nuevo `/ticket panel`.", "✅ Category **{nombre}** removed. Publish `/ticket panel` again.", "✅ Catégorie **{nombre}** supprimée. Republie `/ticket panel`.", "✅ Kategorie **{nombre}** entfernt. Veröffentliche `/ticket panel` erneut.", "✅ Categoria **{nombre}** eliminada. Volta a publicar `/ticket panel`.", "✅ Categoria **{nombre}** rimossa. Ripubblica `/ticket panel`.", "✅ カテゴリ **{nombre}** を削除しました。`/ticket panel` を再投稿してください。", "✅ 카테고리 **{nombre}**이(가) 삭제되었습니다. `/ticket panel`을 다시 게시하세요.", "✅ 已删除分类 **{nombre}**。请重新发布 `/ticket panel`。")
A("✅ Categoría **{v0} {v1}** añadida (`{v2}`).\nVuelve a publicar `/ticket panel` para actualizar el selector.{extra}",
  "✅ Categoría **{v0} {v1}** añadida (`{v2}`).\nVuelve a publicar `/ticket panel` para actualizar el selector.{extra}",
  "✅ Category **{v0} {v1}** added (`{v2}`).\nPublish `/ticket panel` again to refresh the dropdown.{extra}",
  "✅ Catégorie **{v0} {v1}** ajoutée (`{v2}`).\nRepublie `/ticket panel` pour mettre à jour le menu.{extra}",
  "✅ Kategorie **{v0} {v1}** hinzugefügt (`{v2}`).\nVeröffentliche `/ticket panel` erneut, um das Menü zu aktualisieren.{extra}",
  "✅ Categoria **{v0} {v1}** adicionada (`{v2}`).\nVolta a publicar `/ticket panel` para atualizar o seletor.{extra}",
  "✅ Categoria **{v0} {v1}** aggiunta (`{v2}`).\nRipubblica `/ticket panel` per aggiornare il menu.{extra}",
  "✅ カテゴリ **{v0} {v1}** を追加 (`{v2}`)。\nセレクタ更新のため `/ticket panel` を再投稿。{extra}",
  "✅ 카테고리 **{v0} {v1}** 추가됨 (`{v2}`).\n선택기를 갱신하려면 `/ticket panel`을 다시 게시하세요.{extra}",
  "✅ 已添加分类 **{v0} {v1}**（`{v2}`）。\n请重新发布 `/ticket panel` 以更新下拉菜单。{extra}")
A("✅ Categorías restauradas. Publica de nuevo `/ticket panel`.", "✅ Categorías restauradas. Publica de nuevo `/ticket panel`.", "✅ Categories restored. Publish `/ticket panel` again.", "✅ Catégories restaurées. Republie `/ticket panel`.", "✅ Kategorien wiederhergestellt. `/ticket panel` erneut veröffentlichen.", "✅ Categorias restauradas. Volta a publicar `/ticket panel`.", "✅ Categorie ripristinate. Ripubblica `/ticket panel`.", "✅ カテゴリを復元しました。`/ticket panel` を再投稿してください。", "✅ 카테고리를 복원했습니다. `/ticket panel`을 다시 게시하세요.", "✅ 已恢复分类。请重新发布 `/ticket panel`。")
A("✅ Cleared all infractions for **{display_name}**. Aviso enviado por MD.", "✅ Borradas todas las infracciones de **{display_name}**. Aviso enviado por MD.", "✅ Cleared all infractions for **{display_name}**. Notice sent by DM.", "✅ Toutes les infractions de **{display_name}** ont été effacées. Avis envoyé en MP.", "✅ Alle Verstöße von **{display_name}** gelöscht. Hinweis per DM.", "✅ Apagadas todas as infrações de **{display_name}**. Aviso enviado por MD.", "✅ Cancellate tutte le infrazioni di **{display_name}**. Avviso inviato in DM.", "✅ **{display_name}** の違反をすべて削除。DMで通知しました。", "✅ **{display_name}**의 위반을 모두 지웠습니다. DM으로 알렸습니다.", "✅ 已清除 **{display_name}** 的全部违规。已通过私信通知。")
A("✅ Compra Exitosa", "✅ Compra exitosa", "✅ Purchase successful", "✅ Achat réussi", "✅ Kauf erfolgreich", "✅ Compra bem-sucedida", "✅ Acquisto riuscito", "✅ 購入成功", "✅ 구매 성공", "✅ 购买成功")
A("✅ Confesión enviada. Nadie verá que fuiste tú.", "✅ Confesión enviada. Nadie verá que fuiste tú.", "✅ Confession sent. Nobody will see it was you.", "✅ Confession envoyée. Personne ne verra que c'était toi.", "✅ Geständnis gesendet. Niemand sieht, dass du es warst.", "✅ Confissão enviada. Ninguém verá que foste tu.", "✅ Confessione inviata. Nessuno vedrà che sei stato tu.", "✅ 告白を送りました。誰にもあなただと分かりません。", "✅ 고백을 보냈습니다. 당신이 보낸 줄 모릅니다.", "✅ 告白已发送。没人会知道是你。")
A("✅ Configuración de color actualizada:\n**Precio:** {precio} monedas | **Duración:** {dur_text}",
  "✅ Configuración de color actualizada:\n**Precio:** {precio} monedas | **Duración:** {dur_text}",
  "✅ Colour settings updated:\n**Price:** {precio} coins | **Duration:** {dur_text}",
  "✅ Réglages de couleur mis à jour :\n**Prix :** {precio} pièces | **Durée :** {dur_text}",
  "✅ Farbeinstellungen aktualisiert:\n**Preis:** {precio} Münzen | **Dauer:** {dur_text}",
  "✅ Definições de cor atualizadas:\n**Preço:** {precio} moedas | **Duração:** {dur_text}",
  "✅ Impostazioni colore aggiornate:\n**Prezzo:** {precio} monete | **Durata:** {dur_text}",
  "✅ 色設定を更新:\n**価格:** {precio} コイン | **期間:** {dur_text}",
  "✅ 색상 설정이 업데이트됨:\n**가격:** {precio} 코인 | **기간:** {dur_text}",
  "✅ 已更新颜色设置：\n**价格：** {precio} 金币 | **时长：** {dur_text}")
A("✅ Configuración de trivia actualizada:\n**Canal:** {mention}\n**Premio:** {premio} monedas\n**Auto-envío:** {status}",
  "✅ Configuración de trivia actualizada:\n**Canal:** {mention}\n**Premio:** {premio} monedas\n**Auto-envío:** {status}",
  "✅ Trivia settings updated:\n**Channel:** {mention}\n**Prize:** {premio} coins\n**Auto-send:** {status}",
  "✅ Réglages trivia mis à jour :\n**Salon :** {mention}\n**Prix :** {premio} pièces\n**Envoi auto :** {status}",
  "✅ Trivia-Einstellungen aktualisiert:\n**Kanal:** {mention}\n**Preis:** {premio} Münzen\n**Auto-Versand:** {status}",
  "✅ Definições de trivia atualizadas:\n**Canal:** {mention}\n**Prémio:** {premio} moedas\n**Envio automático:** {status}",
  "✅ Impostazioni trivia aggiornate:\n**Canale:** {mention}\n**Premio:** {premio} monete\n**Invio auto:** {status}",
  "✅ トリビア設定を更新:\n**チャンネル:** {mention}\n**賞品:** {premio} コイン\n**自動送信:** {status}",
  "✅ 퀴즈 설정이 업데이트됨:\n**채널:** {mention}\n**보상:** {premio} 코인\n**자동 전송:** {status}",
  "✅ 已更新问答设置：\n**频道：** {mention}\n**奖励：** {premio} 金币\n**自动发送：** {status}")
A("✅ Configuration imported successfully!", "✅ Configuración importada.", "✅ Configuration imported successfully!", "✅ Configuration importée.", "✅ Konfiguration importiert.", "✅ Configuração importada.", "✅ Configurazione importata.", "✅ 設定をインポートしました。", "✅ 설정을 가져왔습니다.", "✅ 已导入配置。")
A("✅ Configuration saved! Now select the roles to include using the dropdown below.", "✅ Configuración guardada. Elige ahora los roles en el desplegable.", "✅ Configuration saved! Now select the roles to include using the dropdown below.", "✅ Config enregistrée. Choisis les rôles dans le menu ci-dessous.", "✅ Konfiguration gespeichert. Wähle die Rollen im Dropdown.", "✅ Configuração guardada. Escolhe agora os cargos no menu.", "✅ Configurazione salvata. Seleziona i ruoli dal menu sotto.", "✅ 設定を保存しました。下のメニューからロールを選んでください。", "✅ 설정을 저장했습니다. 아래 메뉴에서 역할을 고르세요.", "✅ 已保存配置。请用下面的下拉菜单选择身份组。")
A("✅ Correct color! ({v0})", "✅ ¡Color correcto! ({v0})", "✅ Correct color! ({v0})", "✅ Bonne couleur ! ({v0})", "✅ Richtige Farbe! ({v0})", "✅ Cor certa! ({v0})", "✅ Colore giusto! ({v0})", "✅ 色が正解！({v0})", "✅ 색이 맞아요! ({v0})", "✅ 颜色正确！({v0})")
A("✅ Correct! {number} is EVEN!", "✅ ¡Correcto! {number} es PAR.", "✅ Correct! {number} is EVEN!", "✅ Correct ! {number} est PAIR !", "✅ Richtig! {number} ist GERADE!", "✅ Certo! {number} é PAR!", "✅ Giusto! {number} è PARI!", "✅ 正解！{number} は偶数！", "✅ 정답! {number}은(는) 짝수!", "✅ 正确！{number} 是偶数！")
A("✅ Correct! {number} is ODD!", "✅ ¡Correcto! {number} es IMPAR.", "✅ Correct! {number} is ODD!", "✅ Correct ! {number} est IMPAIR !", "✅ Richtig! {number} ist UNGERADE!", "✅ Certo! {number} é ÍMPAR!", "✅ Giusto! {number} è DISPARI!", "✅ 正解！{number} は奇数！", "✅ 정답! {number}은(는) 홀수!", "✅ 正确！{number} 是奇数！")
A("✅ Custom background set for guild {gid}.", "✅ Fondo personalizado fijado para el servidor {gid}.", "✅ Custom background set for guild {gid}.", "✅ Fond personnalisé défini pour le serveur {gid}.", "✅ Eigener Hintergrund für Gilde {gid} gesetzt.", "✅ Fundo personalizado definido para o servidor {gid}.", "✅ Sfondo personalizzato impostato per la guild {gid}.", "✅ サーバー {gid} のカスタム背景を設定しました。", "✅ 길드 {gid}의 사용자 지정 배경이 설정되었습니다.", "✅ 已为服务器 {gid} 设置自定义背景。")
A("✅ Database backed up to `{dst}`", "✅ Base de datos copiada en `{dst}`", "✅ Database backed up to `{dst}`", "✅ Base sauvegardée vers `{dst}`", "✅ Datenbank nach `{dst}` gesichert.", "✅ Base de dados copiada para `{dst}`", "✅ Database salvato in `{dst}`", "✅ データベースを `{dst}` にバックアップしました。", "✅ 데이터베이스가 `{dst}`에 백업되었습니다.", "✅ 数据库已备份到 `{dst}`")
A("✅ Deleted case #{case_id}. El usuario ha sido avisado por MD si era posible.", "✅ Borrado el caso #{case_id}. El usuario ha sido avisado por MD si era posible.", "✅ Deleted case #{case_id}. The user was notified by DM if possible.", "✅ Dossier #{case_id} supprimé. L'utilisateur a été prévenu en MP si possible.", "✅ Fall #{case_id} gelöscht. Nutzer per DM benachrichtigt, falls möglich.", "✅ Caso #{case_id} apagado. O utilizador foi avisado por MD se possível.", "✅ Caso #{case_id} eliminato. L'utente è stato avvisato in DM se possibile.", "✅ ケース #{case_id} を削除。可能ならDMで通知しました。", "✅ 사건 #{case_id}을(를) 삭제했습니다. 가능하면 DM으로 알렸습니다.", "✅ 已删除案件 #{case_id}。若可能已通过私信通知用户。")
A("✅ Deleted command `{trigger}`.", "✅ Borrado el comando `{trigger}`.", "✅ Deleted command `{trigger}`.", "✅ Commande `{trigger}` supprimée.", "✅ Befehl `{trigger}` gelöscht.", "✅ Comando `{trigger}` apagado.", "✅ Comando `{trigger}` eliminato.", "✅ コマンド `{trigger}` 를 삭제했습니다。", "✅ 명령 `{trigger}`을(를) 삭제했습니다.", "✅ 已删除命令 `{trigger}`。")
A("✅ Deleted stat channel.", "✅ Canal de stats borrado.", "✅ Deleted stat channel.", "✅ Salon de stats supprimé.", "✅ Statistikkanal gelöscht.", "✅ Canal de stats apagado.", "✅ Canale stats eliminato.", "✅ 統計チャンネルを削除しました。", "✅ 통계 채널이 삭제되었습니다.", "✅ 已删除统计频道。")
A("✅ El logro **{v0}** (`{achievement_id}`) ya no se otorga en este servidor.", "✅ El logro **{v0}** (`{achievement_id}`) ya no se otorga en este servidor.", "✅ Achievement **{v0}** (`{achievement_id}`) is no longer granted in this server.", "✅ Le succès **{v0}** (`{achievement_id}`) n'est plus attribué sur ce serveur.", "✅ Erfolg **{v0}** (`{achievement_id}`) wird auf diesem Server nicht mehr vergeben.", "✅ A conquista **{v0}** (`{achievement_id}`) já não é dada neste servidor.", "✅ L'obiettivo **{v0}** (`{achievement_id}`) non viene più assegnato in questo server.", "✅ 実績 **{v0}** (`{achievement_id}`) はこのサーバーでは付与されません。", "✅ 업적 **{v0}** (`{achievement_id}`)은(는) 이 서버에서 더 이상 지급되지 않습니다.", "✅ 成就 **{v0}**（`{achievement_id}`）不再在此服务器发放。")
A("✅ El rol {mention} ha sido retirado de la tienda.", "✅ El rol {mention} ha sido retirado de la tienda.", "✅ Role {mention} was removed from the shop.", "✅ Le rôle {mention} a été retiré de la boutique.", "✅ Rolle {mention} wurde aus dem Shop genommen.", "✅ O cargo {mention} foi retirado da loja.", "✅ Il ruolo {mention} è stato rimosso dal negozio.", "✅ ロール {mention} をショップから外しました。", "✅ 역할 {mention}이(가) 상점에서 제거되었습니다.", "✅ 已从商店移除身份组 {mention}。")
A("✅ Fondo de Bienvenida Actualizado", "✅ Fondo de bienvenida actualizado", "✅ Welcome background updated", "✅ Fond de bienvenue mis à jour", "✅ Willkommen-Hintergrund aktualisiert", "✅ Fundo de boas-vindas atualizado", "✅ Sfondo di benvenuto aggiornato", "✅ 歓迎背景を更新しました", "✅ 환영 배경이 업데이트되었습니다", "✅ 已更新欢迎背景")
A("✅ Giveaway ended!", "✅ ¡Sorteo finalizado!", "✅ Giveaway ended!", "✅ Giveaway terminé !", "✅ Giveaway beendet!", "✅ Sorteio terminado!", "✅ Giveaway terminato!", "✅ ギブアウェイ終了！", "✅ 기브어웨이가 끝났습니다!", "✅ 抽奖已结束！")
A("✅ Goodbye Channel Set", "✅ Canal de despedida fijado", "✅ Goodbye Channel Set", "✅ Salon d'au revoir défini", "✅ Abschiedskanal gesetzt", "✅ Canal de despedida definido", "✅ Canale di uscita impostato", "✅ 退室チャンネルを設定", "✅ 작별 채널이 설정됨", "✅ 已设置离开频道")
A("✅ Goodbye Message Updated", "✅ Mensaje de despedida actualizado", "✅ Goodbye Message Updated", "✅ Message d'au revoir mis à jour", "✅ Abschiedsnachricht aktualisiert", "✅ Mensagem de despedida atualizada", "✅ Messaggio di uscita aggiornato", "✅ 退室メッセージを更新", "✅ 작별 메시지가 업데이트됨", "✅ 已更新离开消息")
A("✅ Joined **{name}** and ready to speak! Use `/tts toggle` to link a chat channel.", "✅ Unido a **{name}** y listo para hablar. Usa `/tts toggle` para ligar un canal de chat.", "✅ Joined **{name}** and ready to speak! Use `/tts toggle` to link a chat channel.", "✅ Rejoint **{name}** et prêt à parler. Utilise `/tts toggle` pour lier un salon.", "✅ **{name}** beigetreten und bereit zu sprechen. Nutze `/tts toggle`, um einen Chatkanal zu koppeln.", "✅ Entrei em **{name}** e estou pronto a falar. Usa `/tts toggle` para ligar um canal de chat.", "✅ Entrato in **{name}** e pronto a parlare. Usa `/tts toggle` per collegare un canale.", "✅ **{name}** に参加し、話せる状態です。`/tts toggle` でチャットチャンネルを紐づけてください。", "✅ **{name}**에 들어갔고 말할 준비됨. `/tts toggle`로 채팅 채널을 연결하세요.", "✅ 已加入 **{name}**，可以说话。用 `/tts toggle` 绑定聊天频道。")
A("✅ Las detecciones de multicuenta se enviarán a {mention} con botones para aprobar, denegar, banear o permitir siempre.",
  "✅ Las detecciones de multicuenta se enviarán a {mention} con botones para aprobar, denegar, banear o permitir siempre.",
  "✅ Multi-account detections will go to {mention} with buttons to approve, deny, ban or always-allow.",
  "✅ Les détections de multi-comptes iront dans {mention} avec des boutons pour approuver, refuser, bannir ou toujours autoriser.",
  "✅ Mehrfachkonto-Erkennungen gehen an {mention} mit Buttons zum Freigeben, Ablehnen, Bannen oder immer Erlauben.",
  "✅ As deteções de multiconta vão para {mention} com botões para aprovar, recusar, banir ou permitir sempre.",
  "✅ I rilevamenti multi-account andranno in {mention} con pulsanti per approvare, negare, bannare o consentire sempre.",
  "✅ マルチアカウント検出は {mention} に送られ、承認・拒否・BAN・常時許可のボタンが付きます。",
  "✅ 다중 계정 감지가 {mention}(으)로 가며 승인, 거부, 차단, 항상 허용 버튼이 있습니다.",
  "✅ 多账号检测会发到 {mention}，带批准、拒绝、封禁或始终允许按钮。")
A("✅ Logro `{achievement_id}` restaurado en este servidor.", "✅ Logro `{achievement_id}` restaurado en este servidor.", "✅ Achievement `{achievement_id}` restored in this server.", "✅ Succès `{achievement_id}` restauré sur ce serveur.", "✅ Erfolg `{achievement_id}` auf diesem Server wiederhergestellt.", "✅ Conquista `{achievement_id}` restaurada neste servidor.", "✅ Obiettivo `{achievement_id}` ripristinato in questo server.", "✅ このサーバーで実績 `{achievement_id}` を復元しました。", "✅ 이 서버에서 업적 `{achievement_id}`을(를) 복원했습니다.", "✅ 已在此服务器恢复成就 `{achievement_id}`。")
A("✅ Logs de tickets en {mention}. Nombre + enlace web en cada apertura.", "✅ Logs de tickets en {mention}. Nombre + enlace web en cada apertura.", "✅ Ticket logs in {mention}. Name + web link on every open.", "✅ Journaux de tickets dans {mention}. Nom + lien web à chaque ouverture.", "✅ Ticket-Logs in {mention}. Name + Weblink bei jeder Öffnung.", "✅ Logs de tickets em {mention}. Nome + ligação web em cada abertura.", "✅ Log dei ticket in {mention}. Nome + link web a ogni apertura.", "✅ チケットログは {mention}。開くたびに名前とウェブリンク。", "✅ 티켓 로그는 {mention}. 열릴 때마다 이름과 웹 링크.", "✅ 工单日志在 {mention}。每次开启都有名称和网页链接。")
A("✅ Logs de tickets en {mention}: nombre del ticket + enlace a {DASHBOARD_URL}.", "✅ Logs de tickets en {mention}: nombre del ticket + enlace a {DASHBOARD_URL}.", "✅ Ticket logs in {mention}: ticket name + link to {DASHBOARD_URL}.", "✅ Journaux de tickets dans {mention} : nom + lien vers {DASHBOARD_URL}.", "✅ Ticket-Logs in {mention}: Name + Link zu {DASHBOARD_URL}.", "✅ Logs de tickets em {mention}: nome + ligação para {DASHBOARD_URL}.", "✅ Log dei ticket in {mention}: nome + link a {DASHBOARD_URL}.", "✅ チケットログは {mention}: 名前 + {DASHBOARD_URL} へのリンク。", "✅ 티켓 로그는 {mention}: 이름 + {DASHBOARD_URL} 링크.", "✅ 工单日志在 {mention}：名称 + {DASHBOARD_URL} 链接。")
A("✅ Mensaje de bienvenida actualizado:\n`{mensaje}`", "✅ Mensaje de bienvenida actualizado:\n`{mensaje}`", "✅ Welcome message updated:\n`{mensaje}`", "✅ Message de bienvenue mis à jour :\n`{mensaje}`", "✅ Willkommensnachricht aktualisiert:\n`{mensaje}`", "✅ Mensagem de boas-vindas atualizada:\n`{mensaje}`", "✅ Messaggio di benvenuto aggiornato:\n`{mensaje}`", "✅ 歓迎メッセージを更新:\n`{mensaje}`", "✅ 환영 메시지가 업데이트됨:\n`{mensaje}`", "✅ 已更新欢迎消息：\n`{mensaje}`")
A("✅ Mensaje enviado a través del webhook con éxito.", "✅ Mensaje enviado a través del webhook con éxito.", "✅ Message sent through the webhook.", "✅ Message envoyé via le webhook.", "✅ Nachricht über das Webhook gesendet.", "✅ Mensagem enviada pelo webhook.", "✅ Messaggio inviato tramite webhook.", "✅ Webhookでメッセージを送りました。", "✅ 웹훅으로 메시지를 보냈습니다.", "✅ 已通过 webhook 发送消息。")
A("✅ Note added for **{display_name}**.", "✅ Nota añadida para **{display_name}**.", "✅ Note added for **{display_name}**.", "✅ Note ajoutée pour **{display_name}**.", "✅ Notiz für **{display_name}** hinzugefügt.", "✅ Nota adicionada para **{display_name}**.", "✅ Nota aggiunta per **{display_name}**.", "✅ **{display_name}** のメモを追加しました。", "✅ **{display_name}**에 대한 메모가 추가되었습니다.", "✅ 已为 **{display_name}** 添加备注。")
A("✅ Note saved! You have {v0}/{limit} notes.", "✅ Nota guardada. Tienes {v0}/{limit} notas.", "✅ Note saved! You have {v0}/{limit} notes.", "✅ Note enregistrée. Tu as {v0}/{limit} notes.", "✅ Notiz gespeichert. Du hast {v0}/{limit} Notizen.", "✅ Nota guardada. Tens {v0}/{limit} notas.", "✅ Nota salvata. Hai {v0}/{limit} note.", "✅ メモを保存しました。{v0}/{limit} 件です。", "✅ 메모가 저장되었습니다. {v0}/{limit}개입니다.", "✅ 备注已保存。你有 {v0}/{limit} 条。")
A("✅ Panel created successfully!", "✅ Panel creado.", "✅ Panel created successfully!", "✅ Panneau créé.", "✅ Panel erstellt.", "✅ Painel criado.", "✅ Pannello creato.", "✅ パネルを作成しました。", "✅ 패널이 만들어졌습니다.", "✅ 面板已创建。")
A("✅ Panel de verificación enviado a {mention}.", "✅ Panel de verificación enviado a {mention}.", "✅ Verification panel sent to {mention}.", "✅ Panneau de vérification envoyé dans {mention}.", "✅ Verifizierungspanel nach {mention} gesendet.", "✅ Painel de verificação enviado para {mention}.", "✅ Pannello di verifica inviato in {mention}.", "✅ 認証パネルを {mention} に送りました。", "✅ 인증 패널을 {mention}에 보냈습니다.", "✅ 验证面板已发到 {mention}。")
A("✅ Panel publicado. Se puede borrar el mensaje si no lo quieres.", "✅ Panel publicado. Se puede borrar el mensaje si no lo quieres.", "✅ Panel posted. You can delete the message if you don't want it.", "✅ Panneau publié. Tu peux supprimer le message si tu n'en veux pas.", "✅ Panel veröffentlicht. Du kannst die Nachricht löschen, wenn du sie nicht willst.", "✅ Painel publicado. Podes apagar a mensagem se não a quiseres.", "✅ Pannello pubblicato. Puoi cancellare il messaggio se non lo vuoi.", "✅ パネルを投稿しました。不要ならメッセージを削除できます。", "✅ 패널을 게시했습니다. 싫으면 메시지를 지워도 됩니다.", "✅ 面板已发布。不想要可以删掉这条消息。")
A("✅ Pregunta con ID {id} eliminada con éxito.", "✅ Pregunta con ID {id} eliminada.", "✅ Question ID {id} deleted.", "✅ Question ID {id} supprimée.", "✅ Frage ID {id} gelöscht.", "✅ Pergunta com ID {id} eliminada.", "✅ Domanda ID {id} eliminata.", "✅ ID {id} の質問を削除しました。", "✅ ID {id} 질문이 삭제되었습니다.", "✅ 已删除 ID 为 {id} 的问题。")
A("✅ Pregunta de trivia añadida con éxito.", "✅ Pregunta de trivia añadida.", "✅ Trivia question added.", "✅ Question de trivia ajoutée.", "✅ Trivia-Frage hinzugefügt.", "✅ Pergunta de trivia adicionada.", "✅ Domanda trivia aggiunta.", "✅ トリビア問題を追加しました。", "✅ 퀴즈 문제가 추가되었습니다.", "✅ 已添加问答题目。")
A("✅ Premium **{p}** en **{v1}** hasta `{v2}`.", "✅ Premium **{p}** en **{v1}** hasta `{v2}`.", "✅ Premium **{p}** on **{v1}** until `{v2}`.", "✅ Premium **{p}** sur **{v1}** jusqu'à `{v2}`.", "✅ Premium **{p}** auf **{v1}** bis `{v2}`.", "✅ Premium **{p}** em **{v1}** até `{v2}`.", "✅ Premium **{p}** su **{v1}** fino a `{v2}`.", "✅ **{v1}** の Premium **{p}**、期限 `{v2}`。", "✅ **{v1}**의 Premium **{p}**, `{v2}`까지.", "✅ **{v1}** 的 Premium **{p}**，直到 `{v2}`。")
A("✅ Premium desactivado en `{gid}` (aunque sea servidor del superusuario).", "✅ Premium desactivado en `{gid}` (aunque sea servidor del superusuario).", "✅ Premium disabled on `{gid}` (even if it is a superuser server).", "✅ Premium désactivé sur `{gid}` (même si c'est un serveur superutilisateur).", "✅ Premium auf `{gid}` deaktiviert (auch Superuser-Server).", "✅ Premium desativado em `{gid}` (mesmo sendo servidor do superutilizador).", "✅ Premium disattivato su `{gid}` (anche se è un server superutente).", "✅ `{gid}` の Premium を無効化しました（スーパーユーザーのサーバーでも）。", "✅ `{gid}`에서 Premium을 껐습니다(슈퍼유저 서버여도).", "✅ 已在 `{gid}` 关闭 Premium（即使是超级用户的服务器）。")
A("✅ Premium quitado a `{gid}`.", "✅ Premium quitado a `{gid}`.", "✅ Premium removed from `{gid}`.", "✅ Premium retiré de `{gid}`.", "✅ Premium von `{gid}` entfernt.", "✅ Premium retirado de `{gid}`.", "✅ Premium rimosso da `{gid}`.", "✅ `{gid}` から Premium 을 제거しました。", "✅ `{gid}`에서 Premium을 제거했습니다.", "✅ 已从 `{gid}` 移除 Premium。")
A("✅ Quarantine Configured", "✅ Cuarentena configurada", "✅ Quarantine Configured", "✅ Quarantaine configurée", "✅ Quarantäne eingerichtet", "✅ Quarentena configurada", "✅ Quarantena configurata", "✅ 隔離を設定しました", "✅ 격리가 구성됨", "✅ 已配置隔离")
A("✅ Quarantine system disabled.", "✅ Sistema de cuarentena deshabilitado.", "✅ Quarantine system disabled.", "✅ Système de quarantaine désactivé.", "✅ Quarantänesystem deaktiviert.", "✅ Sistema de quarentena desativado.", "✅ Sistema di quarantena disattivato.", "✅ 隔離システムを無効にしました。", "✅ 격리 시스템이 꺼졌습니다.", "✅ 已关闭隔离系统。")
A("✅ Released {mention} from quarantine.", "✅ {mention} salió de cuarentena.", "✅ Released {mention} from quarantine.", "✅ {mention} sorti de quarantaine.", "✅ {mention} aus der Quarantäne entlassen.", "✅ {mention} libertado da quarentena.", "✅ {mention} uscito dalla quarantena.", "✅ {mention} の隔離を解除しました。", "✅ {mention}을(를) 격리에서 해제했습니다.", "✅ 已将 {mention} 从隔离放出。")
A("✅ Removed auto-response for trigger: `{trigger}`", "✅ Quitada la autorespuesta del activador `{trigger}`", "✅ Removed auto-response for trigger: `{trigger}`", "✅ Réponse auto retirée pour `{trigger}`", "✅ Auto-Antwort für `{trigger}` entfernt", "✅ Autoresposta de `{trigger}` removida", "✅ Autorisposta per `{trigger}` rimossa", "✅ トリガー `{trigger}` の自動応答を削除しました。", "✅ 트리거 `{trigger}`의 자동 응답을 제거했습니다.", "✅ 已移除触发词 `{trigger}` 的自动回复。")
A("✅ Removed button for {name}.", "✅ Quitado el botón de {name}.", "✅ Removed button for {name}.", "✅ Bouton de {name} retiré.", "✅ Button für {name} entfernt.", "✅ Botão de {name} removido.", "✅ Pulsante di {name} rimosso.", "✅ {name} のボタンを外しました。", "✅ {name} 버튼을 제거했습니다.", "✅ 已移除 {name} 的按钮。")
A("✅ Server Restore Complete", "✅ Restauración del servidor completada", "✅ Server Restore Complete", "✅ Restauration du serveur terminée", "✅ Server-Wiederherstellung fertig", "✅ Restauro do servidor concluído", "✅ Ripristino del server completato", "✅ サーバー復元完了", "✅ 서버 복원 완료", "✅ 服务器恢复完成")
A("✅ Sincronizados {v0} comandos globalmente.", "✅ Sincronizados {v0} comandos globalmente.", "✅ Synced {v0} commands globally.", "✅ {v0} commandes synchronisées en global.", "✅ {v0} Befehle global synchronisiert.", "✅ Sincronizados {v0} comandos globalmente.", "✅ Sincronizzati {v0} comandi a livello globale.", "✅ グローバルに {v0} 件のコマンドを同期しました。", "✅ 전역으로 명령 {v0}개를 동기화했습니다.", "✅ 已全局同步 {v0} 条命令。")
A("✅ Sistema de verificación deshabilitado.", "✅ Sistema de verificación deshabilitado.", "✅ Verification system disabled.", "✅ Système de vérification désactivé.", "✅ Verifizierungssystem deaktiviert.", "✅ Sistema de verificação desativado.", "✅ Sistema di verifica disattivato.", "✅ 認証システムを無効にしました。", "✅ 인증 시스템이 꺼졌습니다.", "✅ 已关闭验证系统。")
A("✅ Starboard disabled.", "✅ Starboard desactivado.", "✅ Starboard disabled.", "✅ Starboard désactivé.", "✅ Starboard deaktiviert.", "✅ Starboard desativado.", "✅ Starboard disattivato.", "✅ スターボードを無効にしました。", "✅ 스타보드가 꺼졌습니다.", "✅ 已关闭星标板。")
A("✅ Starboard set to {mention} with limit **{limit}** stars.", "✅ Starboard en {mention} con **{limit}** estrellas.", "✅ Starboard set to {mention} with limit **{limit}** stars.", "✅ Starboard dans {mention} avec **{limit}** étoiles.", "✅ Starboard auf {mention} mit **{limit}** Sternen.", "✅ Starboard em {mention} com **{limit}** estrelas.", "✅ Starboard in {mention} con **{limit}** stelle.", "✅ スターボードは {mention}、下限 **{limit}** スター。", "✅ 스타보드가 {mention}, 최소 **{limit}** 별입니다.", "✅ 星标板设在 {mention}，最少 **{limit}** 星。")
A("✅ Sticker created: **{name}**", "✅ Sticker creado: **{name}**", "✅ Sticker created: **{name}**", "✅ Sticker créé : **{name}**", "✅ Sticker erstellt: **{name}**", "✅ Sticker criado: **{name}**", "✅ Sticker creato: **{name}**", "✅ スタンプ作成: **{name}**", "✅ 스티커 생성: **{name}**", "✅ 已创建贴纸：**{name}**")
A("✅ Stopped tracking `{repo}`.", "✅ Dejé de seguir `{repo}`.", "✅ Stopped tracking `{repo}`.", "✅ Plus de suivi de `{repo}`.", "✅ Überwachung von `{repo}` beendet.", "✅ Deixei de seguir `{repo}`.", "✅ Non seguo più `{repo}`.", "✅ `{repo}` の追跡を停止しました。", "✅ `{repo}` 추적을 중지했습니다.", "✅ 已停止跟踪 `{repo}`。")
A("✅ Stopped tracking stat channel (error: {e}).", "✅ Dejé de seguir el canal de stats (error: {e}).", "✅ Stopped tracking stat channel (error: {e}).", "✅ Plus de suivi du salon de stats (erreur : {e}).", "✅ Statistikkanal nicht mehr überwacht (Fehler: {e}).", "✅ Deixei de seguir o canal de stats (erro: {e}).", "✅ Non seguo più il canale stats (errore: {e}).", "✅ 統計チャンネルの追跡を停止（エラー: {e}）。", "✅ 통계 채널 추적을 중지했습니다(오류: {e}).", "✅ 已停止跟踪统计频道（错误：{e}）。")
A("✅ Stopped tracking {mention}.", "✅ Dejé de seguir a {mention}.", "✅ Stopped tracking {mention}.", "✅ Plus de suivi de {mention}.", "✅ Überwachung von {mention} beendet.", "✅ Deixei de seguir {mention}.", "✅ Non seguo più {mention}.", "✅ {mention} の追跡を停止しました。", "✅ {mention} 추적을 중지했습니다.", "✅ 已停止跟踪 {mention}。")
A("✅ Suggestion Accepted!", "✅ ¡Sugerencia aceptada!", "✅ Suggestion Accepted!", "✅ Suggestion acceptée !", "✅ Vorschlag angenommen!", "✅ Sugestão aceite!", "✅ Suggerimento accettato!", "✅ 提案を承認しました！", "✅ 제안이 수락되었습니다!", "✅ 建议已接受！")
A("✅ Suggestions channel set to {mention}.", "✅ Canal de sugerencias: {mention}.", "✅ Suggestions channel set to {mention}.", "✅ Salon des suggestions : {mention}.", "✅ Vorschlagskanal: {mention}.", "✅ Canal de sugestões: {mention}.", "✅ Canale suggerimenti: {mention}.", "✅ 提案チャンネルは {mention}。", "✅ 제안 채널: {mention}.", "✅ 建议频道设为 {mention}。")
A("✅ Tempbanned **{display_name}** for {duration}.", "✅ Ban temporal a **{display_name}** durante {duration}.", "✅ Tempbanned **{display_name}** for {duration}.", "✅ Ban temporaire de **{display_name}** pour {duration}.", "✅ **{display_name}** temporär gebannt für {duration}.", "✅ Ban temporário de **{display_name}** por {duration}.", "✅ Ban temporaneo di **{display_name}** per {duration}.", "✅ **{display_name}** を {duration} 一時BANしました。", "✅ **{display_name}**을(를) {duration} 동안 임시 차단했습니다.", "✅ 已将 **{display_name}** 临时封禁 {duration}。")
A("✅ Todos los registros de Dabot (multicuentas, **verificaciones**, tickets…) irán a {mention}.",
  "✅ Todos los registros de Dabot (multicuentas, **verificaciones**, tickets…) irán a {mention}.",
  "✅ All Dabot logs (multi-accounts, **verifications**, tickets…) will go to {mention}.",
  "✅ Tous les journaux Dabot (multi-comptes, **vérifications**, tickets…) iront dans {mention}.",
  "✅ Alle Dabot-Logs (Mehrfachkonten, **Verifizierungen**, Tickets…) gehen an {mention}.",
  "✅ Todos os registos do Dabot (multicontas, **verificações**, tickets…) vão para {mention}.",
  "✅ Tutti i log di Dabot (multi-account, **verifiche**, ticket…) andranno in {mention}.",
  "✅ Dabotのログ（マルチアカウント、**認証**、チケット…）は {mention} に送られます。",
  "✅ Dabot 로그(다중 계정, **인증**, 티켓…)가 {mention}(으)로 갑니다.",
  "✅ Dabot 的全部日志（多账号、**验证**、工单…）将发到 {mention}。")
A("✅ Tu color personalizado ha sido removido y tu nombre ha vuelto a la normalidad.",
  "✅ Tu color personalizado ha sido removido y tu nombre ha vuelto a la normalidad.",
  "✅ Your custom colour was removed and your name is back to normal.",
  "✅ Ta couleur perso a été retirée et ton nom est revenu à la normale.",
  "✅ Deine eigene Farbe wurde entfernt und dein Name ist wieder normal.",
  "✅ A tua cor personalizada foi removida e o nome voltou ao normal.",
  "✅ Il tuo colore personalizzato è stato rimosso e il nome è tornato normale.",
  "✅ カスタムカラーを外し、名前を元に戻しました。",
  "✅ 사용자 지정 색이 제거되었고 이름이 원래대로입니다.",
  "✅ 已移除自定义颜色，名称恢复正常。")
A("✅ User <@{user_id}> has been blacklisted from using the bot.", "✅ El usuario <@{user_id}> ya no puede usar el bot.", "✅ User <@{user_id}> has been blacklisted from using the bot.", "✅ <@{user_id}> est sur liste noire du bot.", "✅ <@{user_id}> darf den Bot nicht mehr nutzen.", "✅ O utilizador <@{user_id}> ficou na lista negra do bot.", "✅ L'utente <@{user_id}> è in blacklist del bot.", "✅ <@{user_id}> をボットのブラックリストに入れました。", "✅ <@{user_id}> 사용자가 봇 블랙리스트에 올랐습니다.", "✅ 用户 <@{user_id}> 已被禁止使用机器人。")
A("✅ Voice Hub setup complete! Join {mention} to test.", "✅ Hub de voz listo. Entra en {mention} para probar.", "✅ Voice Hub setup complete! Join {mention} to test.", "✅ Hub vocal prêt. Rejoins {mention} pour tester.", "✅ Voice-Hub fertig. Geh in {mention} zum Testen.", "✅ Hub de voz pronto. Entra em {mention} para testar.", "✅ Hub vocale pronto. Entra in {mention} per provare.", "✅ ボイスハブ設定完了。{mention} に入って試してください。", "✅ 음성 허브 설정 완료! 테스트하려면 {mention}에 들어가세요.", "✅ 语音大厅已就绪。加入 {mention} 测试。")
A("✅ Webhook **{name}** creado en {mention} con éxito.\n**URL:** `{url}`\n**ID:** `{id}`",
  "✅ Webhook **{name}** creado en {mention} con éxito.\n**URL:** `{url}`\n**ID:** `{id}`",
  "✅ Webhook **{name}** created in {mention}.\n**URL:** `{url}`\n**ID:** `{id}`",
  "✅ Webhook **{name}** créé dans {mention}.\n**URL :** `{url}`\n**ID :** `{id}`",
  "✅ Webhook **{name}** in {mention} erstellt.\n**URL:** `{url}`\n**ID:** `{id}`",
  "✅ Webhook **{name}** criado em {mention}.\n**URL:** `{url}`\n**ID:** `{id}`",
  "✅ Webhook **{name}** creato in {mention}.\n**URL:** `{url}`\n**ID:** `{id}`",
  "✅ Webhook **{name}** を {mention} に作成しました。\n**URL:** `{url}`\n**ID:** `{id}`",
  "✅ 웹훅 **{name}**을(를) {mention}에 만들었습니다.\n**URL:** `{url}`\n**ID:** `{id}`",
  "✅ 已在 {mention} 创建 webhook **{name}**。\n**URL：** `{url}`\n**ID：** `{id}`")
A("✅ Webhook con ID `{webhook_id}` eliminado con éxito.", "✅ Webhook con ID `{webhook_id}` eliminado.", "✅ Webhook ID `{webhook_id}` deleted.", "✅ Webhook `{webhook_id}` supprimé.", "✅ Webhook `{webhook_id}` gelöscht.", "✅ Webhook `{webhook_id}` eliminado.", "✅ Webhook `{webhook_id}` eliminato.", "✅ Webhook `{webhook_id}` を削除しました。", "✅ 웹훅 `{webhook_id}`이(가) 삭제되었습니다.", "✅ 已删除 webhook `{webhook_id}`。")
A("✅ Welcome Channel Set", "✅ Canal de bienvenida fijado", "✅ Welcome Channel Set", "✅ Salon de bienvenue défini", "✅ Willkommenskanal gesetzt", "✅ Canal de boas-vindas definido", "✅ Canale di benvenuto impostato", "✅ 歓迎チャンネルを設定", "✅ 환영 채널이 설정됨", "✅ 已设置欢迎频道")
A("✅ Welcome DM Updated", "✅ MD de bienvenida actualizado", "✅ Welcome DM Updated", "✅ MP de bienvenue mis à jour", "✅ Willkommens-DM aktualisiert", "✅ DM de boas-vindas atualizada", "✅ DM di benvenuto aggiornato", "✅ 歓迎DMを更新", "✅ 환영 DM이 업데이트됨", "✅ 已更新欢迎私信")
